version: '3.8'
services:
  eurekaserver:
    image: saif580/eurekaserver
    ports:
      - "8761:8761"
    networks:
      - dampson_network
    environment:
      - spring.application.name=eurekaserver
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=true

  appointments:
    image: saif580/appointments
    ports:
      - "7001:7001"
    networks:
      - dampson_network
    environment:
      - spring.application.name=appointments
      - server.port=7001
      - spring.data.mongodb.uri=mongodb+srv://dampsonhms:dampson%40123@dampsonhms.whxc0yz.mongodb.net/appointments_db?retryWrites=true&w=majority&appName=dampsonhms
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - spring.datasource.url=jdbc:mysql://dampsondb.cvscsscc6mkv.ap-south-1.rds.amazonaws.com/transaction_db
      - spring.datasource.username=root
      - spring.datasource.password=Dampson123
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - stripe.api.key=sk_test_51Mo6H5SGsETocz7J9gOWvNfItXIBVxg2Q9sRpBKt1BmCJZXvj7I1VKol4PcPH7IpVPvlOlqowWJJEsJaj5NhQGJ400BeYXkblj
      - payment.success.url=http://localhost:7001/payment-success
      - payment.cancel.url=http://localhost:7001/payment-failed
      - spring.thymeleaf.prefix=classpath:/templates/
      - spring.thymeleaf.suffix=.html
      - spring.thymeleaf.cache=false
      - logging.level.org.springframework=DEBUG
      - logging.level.com.hms.appointments=DEBUG
      - logging.level.com.stripe=DEBUG
      - logging.level.com.netflix.discovery=DEBUG
      - logging.level.com.netflix.eureka=DEBUG
      - logging.level.org.springframework.cloud.client.loadbalancer=DEBUG
      - logging.level.reactor.netty.http.client=DEBUG
      - logging.level.reactor.netty.http.server=DEBUG
      - spring.profiles.active=default
      - logging.level.org.mongodb.driver=DEBUG

  usersmicroservice:
    image: saif580/usersmicroservice
    ports:
      - "7000:7000"
    networks:
      - dampson_network
    environment:
      - spring.application.name=usersmicroservice
      - server.port=7000
      - spring.datasource.url=jdbc:mysql://dampsondb.cvscsscc6mkv.ap-south-1.rds.amazonaws.com/user_db
      - spring.datasource.username=root
      - spring.datasource.password=Dampson123
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true

  notificationmicroservice:
    image: saif580/notificationmicroservice
    ports:
      - "7003:7003"
    networks:
      - dampson_network
    environment:
      - spring.application.name=notificationmicroservice
      - server.port=7003
      - spring.data.mongodb.uri=mongodb+srv://dampsonhms:dampson%40123@dampsonhms.whxc0yz.mongodb.net/notifications_db?retryWrites=true&w=majority&appName=dampsonhms
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.username=dampsonhms@gmail.com
      - spring.mail.password=fmse txei tghv zleh
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - eurekaserver
      - appointments

  patientsmicroservice:
    image: saif580/patientsmicroservice
    ports:
      - "7002:7002"
    networks:
      - dampson_network
    environment:
      - spring.application.name=patientsmicroservice
      - server.port=7002
      - spring.datasource.url=jdbc:mysql://dampsondb.cvscsscc6mkv.ap-south-1.rds.amazonaws.com/patient_db
      - spring.datasource.username=root
      - spring.datasource.password=Dampson123
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - eurekaserver

  medicalrecordmicroservice:
    image: saif580/medicalrecordmicroservice
    ports:
      - "7006:7006"
    networks:
      - dampson_network
    environment:
      - spring.application.name=medicalrecordmicroservice
      - server.port=7006
      - spring.datasource.url=jdbc:mysql://dampsondb.cvscsscc6mkv.ap-south-1.rds.amazonaws.com/medicalrecords_db
      - spring.datasource.username=root
      - spring.datasource.password=Dampson123
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - eurekaserver

  billingmicroservice:
    image: saif580/billingmicroservice
    ports:
      - "7004:7004"
    networks:
      - dampson_network
    environment:
      - spring.application.name=billingmicroservice
      - server.port=7004
      - spring.datasource.url=jdbc:mysql://dampsondb.cvscsscc6mkv.ap-south-1.rds.amazonaws.com/billing_db
      - spring.datasource.username=root
      - spring.datasource.password=Dampson123
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - eurekaserver

  apigateway:
    image: saif580/apigateway
    ports:
      - "7010:7010"
    networks:
      - dampson_network
    environment:
      - spring.application.name=APIGateway
      - server.port=7010
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
      - spring.main.allow-bean-definition-overriding=true
      - spring.main.web-application-type=reactive
      - spring.cloud.gateway.routes[0].id=users-service
      - spring.cloud.gateway.routes[0].uri=lb://usersmicroservice
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/authenticate,/register,/api/**
      - spring.cloud.gateway.routes[1].id=patients-service
      - spring.cloud.gateway.routes[1].uri=lb://patientsmicroservice
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/patients/**
      - spring.cloud.gateway.routes[2].id=billing-service
      - spring.cloud.gateway.routes[2].uri=lb://billingmicroservice
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/billings/**
      - spring.cloud.gateway.routes[3].id=medicalrecords-service
      - spring.cloud.gateway.routes[3].uri=lb://medicalrecordmicroservice
      - spring.cloud.gateway.routes[3].predicates[0]=Path=/medicalrecords/**
      - spring.cloud.gateway.routes[4].id=appointments-service
      - spring.cloud.gateway.routes[4].uri=lb://appointments
      - spring.cloud.gateway.routes[4].predicates[0]=Path=/appointments/**
      - spring.cloud.gateway.routes[5].id=notifications-service
      - spring.cloud.gateway.routes[5].uri=lb://notificationmicroservice
      - spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://7010/.well-known/jwks.json
      - logging.level.org.springframework.security=DEBUG
      - logging.level.org.springframework.cloud.gateway=DEBUG
      - logging.level.org.springframework.web=DEBUG
      - logging.level.com.hms.usersmicroservice=DEBUG
      - logging.level.org.springframework.cloud.client.loadbalancer=DEBUG
      - logging.level.reactor.netty.http.client=DEBUG
      - logging.level.reactor.netty.http.server=DEBUG
    depends_on:
      - eurekaserver
      - usersmicroservice
      - patientsmicroservice
      - billingmicroservice
      - medicalrecordmicroservice
      - appointments
      - notificationmicroservice
  
  frontend:
    image: saif580/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_EMAILJS_SERVICE_ID=service_9uk09ea
      - REACT_APP_EMAILJS_TEMPLATE_ID=template_ey2ugrk
      - REACT_APP_EMAILJS_USER_ID=4poZ_Sxf-G8tmjq9X
      - REACT_APP_EMAILJS_SERVICE_ID1=service_jecpwr6
      - REACT_APP_EMAILJS_TEMPLATE_ID1=template_7kba0iw
      - REACT_APP_EMAILJS_USER_ID1=-XQ7vmI579XvtO4m_
      - REACT_APP_API_URL=http://localhost:7010
    networks:
      - dampson_network

networks:
  dampson_network:
    driver: bridge
